### ISSUE TITLE
Markbot will not load

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/fastness-fixer#1]
Hi @thatkidmadrid, I believe I removed all of the unnecessary code (used chrome inspect > sources > show coverage). I tried to reduce the size of the snail.SVG but the link always breaks on my website (it's only a 1% difference). Anyway, Markbot will not load, so if I've completed everything, can you manually mark this?
![markbot-not-loading](https://user-images.githubusercontent.com/77508090/140657824-5c133cdf-b3e3-416a-934b-9296b07e9b72.JPG)

**Comment by thatkidmadrid** [comment]
I'll add it manually. Looks good to me

**Comment by emahadzimustafic** [comment]
Thank you!
